appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: W4w2KgI5aU3gEJyl/ctQIBJS/oiXEKLS3DxpBDBXjeSZFPdxYFHRWCnp8vMYE4OTvSfqw7lbyhF/sEQRcyGrbtL+t8oKa7WOqi1sgHhG4CoKh8F9mmpwcysQVCEAlwvzx8azBu/sJ9bPOQRM8DRXcIKNKURoG0cb4Cuck3L9xEgGVcgRjQhkrru5xIk2w3MpMAi8YS/91MHh7/fACdMqix9gB8aOysxTkJhUcAEVbLWRbQro10QDjd1kDOFFmmWQDMIYaSr514NBSVJ8NsrIUtNifK2K4Ge6I2cBVay4NoVplBGbBmbsjsnLR9NjEdD1n53xAvVMAOuB5x2SzlU06zswnWO+9ivhC3cSKcs5sFiLigr2ZecnJv8SjxS8aHOrKfNoVxG2OxCy0tV4lYL13F4FQfhHACN9qhS0LpnTXS7vF+F6aecyNvlb8bhntJNAlUgnqKOsjvwQEGpUp/IuBth7o08DBOdrWPq3XR/b7Sc2ZaImLqaOZw4q5J4NDwuui6wbpg3dtNBKLBH37e+KCJZUQerP4OtHymGtEOlUyVW66STPvFrCIQbbKLRkkif1NjrS2YMPIgtjH9nYpNxlP/8Wlt1YBJC+9pWrLf99aAFzPHKSRHwRf77BZoAPBTeVkHML4nk72zwfBuHu+w0qvVvCSr/AMOcUVWcYpIWoQSc=}
conda_forge_output_validation: true
